parameter_defaults:

  ControllerCount: 3 
  OvercloudControllerFlavor: control 

  ComputeCount: 1 
  OvercloudComputeFlavor: compute 


  ObjectStorageCount: 1 
  OvercloudObjectStorageFlavor: swift-storage 

  NtpServer: '206.108.0.134' 
  NeutronNetworkType: 'vxlan,vlan' 
  NeutronTunnelTypes: 'vxlan' 

  # additional settings

  NovaReservedHostMemory: 1024 
  DockerPuppetProcessCount: 1 

